version: 2

project_name: work

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: work
    main: ./cmd/work
    binary: work
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/huangchao257/work-cli/internal/cli.Version={{.Version}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - docs/install-guide.md

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: huangchao257
    name: work-cli
  draft: false
  prerelease: auto
  extra_files:
    - glob: scripts/install.sh
    - glob: scripts/install.ps1
